[workspace]
members = [
    "assets",
    "jmaxml-rs",
    "jmaxml-wasm",
]
resolver = "3"

[workspace.package]
authors = ["Taku Fukada <naninunenor@gmail.com>"]
version = "0.3.2"
edition = "2024"
repository = "https://github.com/ciscorn/jmaxml"
license = "MIT OR Apache-2.0"
